# Generated by Django 5.2.15 on 2026-06-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_voter_login_locked_until_voter_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter', 'position'], name='votes_user_id_148b28_idx'),
        ),
    ]
